/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'addFeaturedId' : IDL.Func([IDL.Text], [], []),
  'getContactInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getFeaturedIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getQualityLabel' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'removeFeaturedId' : IDL.Func([IDL.Text], [], []),
  'setContactInfo' : IDL.Func([IDL.Text], [], []),
  'setQualityLabel' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'addFeaturedId' : IDL.Func([IDL.Text], [], []),
    'getContactInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getFeaturedIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getQualityLabel' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'removeFeaturedId' : IDL.Func([IDL.Text], [], []),
    'setContactInfo' : IDL.Func([IDL.Text], [], []),
    'setQualityLabel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };